# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import random
from search import search
from PyQt5 import QtCore, QtGui, QtWidgets, Qt
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *


class Ui_MainWindow(object):
    def __init__(self):
        self.searchObj = search("F:\课件\创新实践\data.csv")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(611, 636)
        MainWindow.setWindowTitle("基于图像检索的眼科疾病诊断系统")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.uploadButton = QtWidgets.QPushButton(self.centralwidget)
        self.uploadButton.setGeometry(QtCore.QRect(70, 470, 211, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.uploadButton.setFont(font)
        self.uploadButton.setObjectName("uploadButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 10, 531, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 540, 511, 41))
        self.label_2.setObjectName("label_2")
        self.scanButton = QtWidgets.QPushButton(self.centralwidget)
        self.scanButton.setGeometry(QtCore.QRect(330, 470, 211, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.scanButton.setFont(font)
        self.scanButton.setObjectName("scanButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 90, 611, 321))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("E://UI//pictures//1.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pathLabel = QtWidgets.QLabel(self.centralwidget)
        self.pathLabel.setGeometry(QtCore.QRect(30, 420, 551, 21))
        self.pathLabel.setObjectName("pathLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.actionEnglish = QtWidgets.QAction(MainWindow)
        self.actionEnglish.setObjectName("actionEnglish")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.uploadButton.setText(_translate("MainWindow", "上传图片"))
        self.label.setText(_translate("MainWindow", "基于图像检索的眼科疾病诊断系统"))
        self.label_2.setText(_translate("MainWindow", "请点击“上传图片”上传您想要进行检索的图片，再点击“检索”进行检索"))
        self.scanButton.setText(_translate("MainWindow", "检索"))
        self.pathLabel.setText(_translate("MainWindow", " "))
        self.menu.setTitle(_translate("MainWindow", "关于"))
        self.action.setText(_translate("MainWindow", "中文"))
        self.actionEnglish.setText(_translate("MainWindow", "English"))
        self.action_2.setText(_translate("MainWindow", "项目信息"))

        self.uploadButton.clicked.connect(self.openfile)
        self.scanButton.clicked.connect(self.openwindow)

    def openfile(self):
        openfile_name = QFileDialog.getOpenFileName()
        print(len(openfile_name[0].strip()))
        if len(openfile_name[0].strip()) > 0:
            self.setText(self.pathLabel, openfile_name[0])
            self.label_3.setPixmap(QtGui.QPixmap(openfile_name[0]))

    def openwindow(self):
        # print(self.pathLabel.text())
        # if len(self.pathLabel.text().strip()) > 0:
        try:
            # f=open(self.pathLabel.text())

            self.resultPaths = self.searchObj.search(6, self.pathLabel.text())
            self.secondWindow = QtWidgets.QMainWindow()
            self.secondui = SecondWindow(self.resultPaths)
            self.secondui.setupUi(self.secondWindow)
            self.secondWindow.show()

        except Exception:
            print("cannot open the file")

    @staticmethod
    def setText(label, text):
        label.setText(text)
        label.adjustSize()

class SecondWindow(object):
    def __init__(self, paths):
        self.paths = paths

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 867)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 281, 281))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(self.paths[0]))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 0, 281, 281))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(self.paths[1]))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 280, 281, 281))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(self.paths[2]))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 280, 281, 281))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(self.paths[3]))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 560, 281, 281))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(self.paths[4]))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(280, 560, 281, 281))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(self.paths[5]))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.lastPageButton = QtWidgets.QPushButton(self.centralwidget)
        self.lastPageButton.setGeometry(QtCore.QRect(590, 270, 93, 28))
        self.lastPageButton.setObjectName("lastPageButton")
        self.nextPageButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextPageButton.setGeometry(QtCore.QRect(590, 340, 93, 28))
        self.nextPageButton.setObjectName("nextPageButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lastPageButton.setText(_translate("MainWindow", "上一页"))
        self.nextPageButton.setText(_translate("MainWindow", "下一页"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
